services:
  p1:
    build: .  
    command: ["python", "-u", "source.py"]
    stdin_open: true
    container_name: TCP_PERSON_ONE
    volumes:
      - ./p1_data:/app/data

  p2:
    build: .
    command: ["python", "-u", "source.py"]
    stdin_open: true
    container_name: TCP_PERSON_TWO
    volumes:
      - ./p2_data:/app/data
    