
  services:
    bobby:
      build: .
      command: ["python", "-u", "source.py"]
      stdin_open: true
      container_name: bobby
      volumes:
        - ./bobby:/app/data
    alice:
      build: .
      command: ["python", "-u", "source.py"]
      stdin_open: true
      container_name: alice
      volumes:
        - ./alice:/app/data
      