services:
  central_service:
    build: .  
    command: ["python", "-u", "servers/centralServer.py"]

  user_node:
    build: .
    command: ["python", "-u", "servers/theClientSide.py"]
    stdin_open: true
    container_name: TCP_PERSON_TWO
    volumes:
      - ./node:/app/data
    